#!/bin/bash

SESSION=`basename "$0"`
TARGET="$SESSION:dashboard"

tmux -2 new-session   -d -s "$SESSION" -n "dashboard" -c "$HOME"
X=`tmux list-panes -t $TARGET | wc -l`
echo $X
if (( $X < 2 ));then
tmux -2 split-window  -ht $TARGET   -l 81
tmux -2 split-window  -vt $TARGET.1 -l 53
tmux -2 split-window  -vt $TARGET.2 -l 28
sleep 0.1 && tmux -2 resize-pane -t $TARGET.1 -x 85 &
sleep 0.5 && tmux -2 send-keys -t $TARGET.0 "clear" C-m &
sleep 0.5 && tmux -2 send-keys -t $TARGET.1 "clear" C-m &
sleep 0.5 && tmux -2 send-keys -t $TARGET.1 "uprecords" C-m &
sleep 0.5 && tmux -2 send-keys -t $TARGET.2 "clear" C-m &
sleep 0.5 && tmux -2 send-keys -t $TARGET.2 "ntpstats" C-m &
sleep 0.5 && tmux -2 send-keys -t $TARGET.3 "top" C-m &
tmux -2 select-pane   -t $TARGET.0
tmux -2 select-window -t  $TARGET
fi
