#!/bin/bash
echo "KRSTUFF: Reading local homes"

# Set up environment specific to this system.
# Values here override things in the default krstuff config, so this can be sparse.
# This is a callback from standard krstuff.

export KRSTUFF_HOME=/usr/local/krstuff

export ANT_HOME=/opt/ant/current
export ARTIFACTORY_HOME=/opt/artifactory/current
export CLASSPATH=../9ci-app-conf
export GANT_HOME=/opt/gant/current
export JAVA_HOME=/Library/Java/JavaVirtualMachines/jdk1.7.0_51.jdk/Contents/Home
export MULTIMARKDOWN_HOME=/opt/multimarkdown/current
export MYSQL_HOME=/usr/local/mysql
export NODE_HOME=/usr/local/bin/npm
export PHANTOMJS_HOME=/opt/phantomjs/current

echo "KRSTUFF: Done reading local homes"
