#!/bin/bash
# This is the first file in KRSTUFF.  It needs to be non-versioned so it can be modified to the system.

export KRSTUFF_HOME=/usr/local/krstuff
export KRSTUFF_LOCAL_ETC=/etc/krstuff

# Go set it all up.
# profile will read:
#   1. $KRSTUFF_HOME/etc/homes
#   2. $KRSTUFF_LOCAL_ETC/homes
#   3. $KRSTUFF_HOME/etc/env
#   4. $KRSTUFF_HOME/etc/aliases
#   5. $KRSTUFF_LOCAL_ETC/env
#   6. $KRSTUFF_LOCAL_ETC/aliases
[[ -s "$KRSTUFF_HOME/etc/profile" ]] && source "$KRSTUFF_HOME/etc/profile"
