#!/bin/bash
# Aliases I want on every system.
[[ -n "$KRSTUFF_LOG" ]]	&& echo "Entering ${BASH_SOURCE[0]}"

function make_and_change_dir {
	/bin/mkdir -p "$1"
	cd "$1"
}
alias mcd=make_and_change_dir

# System-specific aliases
alias c='clear'
alias bb="$BROWSER"
alias df='df -h'

UNAME="`uname -s`"
if [ "$UNAME" = 'Darwin' ]; then
	alias ll='ls -alhG'
	alias err='open target/test-reports/html/index.html'
elif [ "$UNAME" = 'Linux' ]; then
	alias ll='ls --color -alh'
	alias err='$BROWSER target/test-reports/html/index.html'
fi
alias ps='/bin/ps axf'
alias psj='/bin/ps axf | grep java'
alias psg='/bin/ps axf | grep'
alias rdesktop='/usr/bin/rdesktop -a 16 -g 1918x1020 -r disk:w=/home/ken/ws -r disk:v=/home/ken/Documents/Clients'
alias rdp='/usr/bin/rdesktop -a 16 -g 1918x1020 -r disk:w=/home/ken/ws -r disk:v=/home/ken/Documents/Clients'

# Git related aliases
alias gittagdate='git log --tags --simplify-by-decoration --pretty="format:%ci %d"'
alias gittagseq='git log --tags --oneline --decorate --simplify-by-decoration'
alias glog='git log -n 5'
alias ggl='git log --graph --oneline -n 20'
alias gprl='git pull --rebase --log'
alias slog='svn log | head -n 50'
alias gco='git checkout'
alias gcom='git checkout master'
alias grpo='git remote prune origin'
alias gba='git branch -a'
alias gs='git status'

# Grails development related aliases.
alias cdt='cd ~/ws/master/head'

GRAILS="gg"
alias glbl='less target/build.log'
alias g=$GRAILS
alias gca="$GRAILS clean"
alias gc="$GRAILS compile"
alias gsc='echo "SUPERCLEAN Removing .grails target, stacktrace.log and all the plugin.xml files";rm -rf .grails target stacktrace.log ../*/plugin.xml'
alias gssc='echo "SUPERSUPERCLEAN .grails target, stacktrace.log, all the plugin.xml files, ivy2 and grails tmp directories";rm -rf .grails target stacktrace.log ../*/plugin.xml ~/.ivy2 ~/.grails/ivy-cache ~/.grails/2.*/'



alias gec='$EDITOR application.properties grails-app/conf/BuildConfig.groovy'
alias gra="$GRAILS -Ddisable.auto.recompile=false run-app"
alias grat="$GRAILS test run-app"
alias grw="$GRAILS run-war"
alias gta="$GRAILS test-app -echoOut"

# grails database targets for older databases
alias gdevdb="grails  -DBMS=my dev create-db clean --non-interactive=y;grails -DBMS=my dev dbm-update"
alias gpdevdb="grails -DBMS=ms dev create-db clean --non-interactive=y;grails -DBMS=ms dev dbm-update"
alias gphistdb="grails -DBMS=ms -Dgrails.env=hist create-db clean --non-interactive=y;grails -DBMS=ms -Dgrails.env=hist dbm-update"
alias gtestdb="grails  -DBMS=my test create-db clean --non-interactive=y;grails -DBMS=my test dbm-update"
alias gptestdb="grails -DBMS=ms test create-db clean --non-interactive=y;grails -DBMS=ms test dbm-update"
alias gproddb="grails prod create-db clean --non-interactive=y"

# grails database targets for newer databases.
alias gtdb="$GRAILS  -DBMS=my test db-create"
alias gddb="$GRAILS  -DBMS=my dev db-create"
alias ghdb='$GRAILS  -DBMS=my -Dgrails.env=hist db-create'
alias gpddb="$GRAILS -DBMS=ms dev db-create"
alias gphdb='$GRAILS -DBMS=ms -Dgrails.env=hist db-create'
alias gptdb="$GRAILS -DBMS=ms test db-create"

alias si='svn info'
alias ss='svn status'
alias sss='svn update;svn status'
alias sd='svn diff'
alias sl='svn log -l 10'
alias st='/Applications/Sublime\ Text\ 2.app/Contents/MacOS/Sublime\ Text\ 2'
alias sup='/opt/subversion/bin/svn up'
alias tcq='$CATALINA_HOME/bin/shutdown.sh'
alias tcr='rm -rf $CATALINA_HOME/temp/* $CATALINA_HOME/work/* $CATALINA_HOME/logs/*;$CATALINA_HOME/bin/startup.sh;tail -n 1000 -F $CATALINA_HOME/logs/catalina.out'
#alias rmsvn='rm -rf `find . -type d -name .svn`'
alias xnc='Xnest -query 192.168.1.100 -geometry 1920x1020'

[[ -n "$KRSTUFF_LOG" ]]	&& echo "Leaving ${BASH_SOURCE[0]}"
