#!/bin/bash
# Defines HOME variables for grails/java add-ons.
# You can either use my scheme for installing these things or copy these configurations to your .bash_profile and edit.
# In my schema, /opt/ant contains all ant installations, and 'current' is a symbolic link to the one you want to use.

export ANT_HOME='/opt/ant/current'
export CATALINA_HOME='/opt/tomcat6/current'
export ECLIPSE_HOME='~/eclipse'
export GANT_HOME='/opt/gant/current'
export GRAILS_HOME='/opt/grails/current'
export GROOVY_HOME='/opt/groovy/current'
export JAVA_HOME="/Library/Java/Home"
export MDP_HOME="/Users/ken/src/markdown-plus"
export MULTIMARKDOWN_HOME='/opt/multimarkdown/current'

# These are OPTS variables for the above.
export GRAILS_OPTS='-Xmx1024M -XX:MaxPermSize=256m'
export JAVA_OPTS="-Xmx768m -XX:MaxPermSize=256m"

# PATHS are done here because of the inherent relation to HOMEs
export SYSPATH=/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/bin:/usr/X11/bin
export PATH=".:\
$HOME/bin:\
$KRSTUFF_HOME/bin:\
$ANT_HOME/bin:\
$CATALINA_HOME/bin:\
$ECLIPSE_HOME/bin:\
$GRAILS_HOME/bin:\
$GROOVY_HOME/bin:\
$GANT_HOME/bin:\
/opt/local/bin:\
/opt/local/sbin:\
/usr/local/mysql/bin:\
/opt/subversion/bin:\
$MULTIMARKDOWN_HOME/bin:\
$MDP_HOME:\
$SYSPATH"

# CDPATH is the path used for the 'cd' command.  First come, first served so '.' should always be first!
#export CDPATH='.:$HOME:$HOME/ws:$HOME/Workspaces:/opt'