#!/bin/bash

echo "Reading $KRSTUFF_HOME/etc/homes"

# GVM homes.
GAIDEN_HOME=$HOME/.gvm/gaiden/current
GLIDE_HOME=$HOME/.gvm/glide/current
GRADLE_HOME=$HOME/.gvm/gradle/current
GRAILS_HOME=$HOME/.gvm/grails/current
GRIFFON_HOME=$HOME/.gvm/griffon/current
GROOVYSERV_HOME=$HOME/.gvm/groovyserv/current
GROOVY_HOME=$HOME/.gvm/groovy/current
JBAKE_HOME=$HOME/.gvm/jbake/current
LAZYBONES_HOME=$HOME/.gvm/lazybones/current
SPRINGBOOT_HOME=$HOME/.gvm/springboot/current
VERTX_HOME=$HOME/.gvm/vertx/current

GVM_PATH=$GAIDEN_HOME/bin:$GLIDE_HOME/bin:$GRADLE_HOME/bin:$GRAILS_HOME/bin:$GRIFFON_HOME/bin:$GROOVYSERV_HOME/bin:$GROOVY_HOME/bin:$JBAKE_HOME/bin:$LAZYBONES_HOME/bin:$SPRINGBOOT_HOME/bin:$VERTX_HOME/bin:

export GAIDEN_HOME GLIDE_HOME GRADLE_HOME GRAILS_HOME GRIFFON_HOME GROOVYSERV_HOME GROOVY_HOME JBAKE_HOME LAZYBONES_HOME SPRINGBOOT_HOME VERTX_HOME GVM_PATH
