#!bin/bash
# Ken Roberts 2010-11-02

# Read in standard homes
[[ -s "$KRSTUFF_HOME/etc/homes"    ]] && source "$KRSTUFF_HOME/etc/homes"

# Read in local homes
[[ -s "$KRSTUFF_LOCAL_ETC/homes"   ]] && source "$KRSTUFF_LOCAL_ETC/homes"

if [ `id -u` = 0 ]; then
	# This is root user, don't take '.' in path.
        KR_PATH="$HOME/bin:$KRSTUFF_HOME/bin"
else
	# This is a normal user, '.' is OK.
        KR_PATH=".:$HOME/bin:$KRSTUFF_HOME/bin"
fi

[[ -s "$KRSTUFF_HOME/etc/env"      ]] && source "$KRSTUFF_HOME/etc/env"
[[ -s "$KRSTUFF_HOME/etc/aliases"  ]] && source "$KRSTUFF_HOME/etc/aliases"

# Pull in the mac-standard development tools.  You should be doing this in .bash_profile, but do it AFTER the things in krstuff.
#if [ -f /opt/local/etc/bash_completion ]; then
#    . /opt/local/etc/bash_completion
#fi

[[ -s "$KRSTUFF_LOCAL_ETC/env"     ]] && source "$KRSTUFF_LOCAL_ETC/env"
[[ -s "$KRSTUFF_LOCAL_ETC/aliases" ]] && source "$KRSTUFF_LOCAL_ETC/aliases"
