#!/bin/bash

SESSION=`basename "$0"`
TARGET="$SESSION:dashboard"
BASEDIR="$HOME"

tmux -2 new-session   -d -s "$SESSION" -n "dashboard" -c "$HOME"
tmux -2 new-window    -kt $SESSION:1  -c $BASEDIR/.ivy2         -n .ivy2
tmux -2 new-window    -kt $SESSION:2  -c $BASEDIR/.kube/configs -n .kube/configs
tmux -2 new-window    -kt $SESSION:3  -c $BASEDIR/.m2           -n .m2
tmux -2 new-window    -kt $SESSION:4  -c $BASEDIR/.ssh          -n .ssh
tmux -2 new-window    -kt $SESSION:5  -c $BASEDIR/Desktop       -n Desktop
tmux -2 new-window    -kt $SESSION:6  -c $BASEDIR/Documents     -n Documents
tmux -2 new-window    -kt $SESSION:7  -c $BASEDIR/Downloads     -n Downloads
tmux -2 new-window    -kt $SESSION:8  -c $BASEDIR/Pictures      -n Pictures
tmux -2 new-window    -kt $SESSION:9  -c $BASEDIR/src           -n src
tmux -2 select-window -t $SESSION:7

# X=`tmux list-panes -t $TARGET | wc -l`
# echo $X
# if (( $X < 2 ));then
# tmux -2 split-window  -ht $TARGET   -l 81
# tmux -2 split-window  -vt $TARGET.1 -l 53
# tmux -2 split-window  -vt $TARGET.2 -l 28
# sleep 0.1 && tmux -2 resize-pane -t $TARGET.1 -x 85 &
# sleep 0.5 && tmux -2 send-keys -t $TARGET.0 "clear" C-m &
# sleep 0.5 && tmux -2 send-keys -t $TARGET.1 "clear" C-m &
# sleep 0.5 && tmux -2 send-keys -t $TARGET.1 "uprecords" C-m &
# sleep 0.5 && tmux -2 send-keys -t $TARGET.2 "clear" C-m &
# sleep 0.5 && tmux -2 send-keys -t $TARGET.2 "ntpstats" C-m &
# sleep 0.5 && tmux -2 send-keys -t $TARGET.3 "top" C-m &
# tmux -2 select-pane   -t $TARGET.0
# tmux -2 select-window -t  $TARGET
# fi
