#!/bin/bash

SESSION=`basename "$0"`
BASEDIR="$HOME/ws/97/971-sherwin"
alias cd971="cd $BASEDIR"

tmux -2 new-session   -d -s "$SESSION" -c "$BASEDIR" -n "$BASEDIR"
tmux -2 new-window     -kt $SESSION:1  -c "$BASEDIR/rootLocation" -n "rootLocation"
tmux -2 new-window     -kt $SESSION:2  -c "$BASEDIR/nine-db"      -n "nine-db"
tmux -2 new-window     -kt $SESSION:3  -c "$BASEDIR/rally"        -n "rally"
tmux -2 new-window     -kt $SESSION:4  -c "$BASEDIR/ar"           -n "ar"
tmux -2 new-window     -kt $SESSION:5  -c "$BASEDIR/autocash"     -n "cash"
tmux -2 new-window     -kt $SESSION:6  -c "$BASEDIR/ar-api"       -n "arapi"
tmux -2 select-window  -t $SESSION:2
