#!/bin/bash

SESSION=`basename "$0"`
BASEDIR="$HOME/ws/99/993y"
alias cd993="cd $BASEDIR"

tmux -2 new-session   -d -s "$SESSION" -c "$BASEDIR" -n "$BASEDIR"
tmux -2 new-window     -kt $SESSION:1  -c "$BASEDIR/rootLocation"     -n "rootLocation"
tmux -2 new-window     -kt $SESSION:2  -c "$BASEDIR/nine-db"          -n "nine-db"
tmux -2 new-window     -kt $SESSION:3  -c "$BASEDIR/rally"            -n "rally"
tmux -2 new-window     -kt $SESSION:4  -c "$BASEDIR/ar"               -n "ar"
tmux -2 new-window     -kt $SESSION:5  -c "$BASEDIR/autocash"         -n "cash"
tmux -2 new-window     -kt $SESSION:6  -c "$BASEDIR/payment-gateway"  -n "pg"
tmux -2 new-window     -kt $SESSION:7  -c "$BASEDIR/epay"             -n "epay"
tmux -2 new-window     -kt $SESSION:8  -c "$BASEDIR/rcm"              -n "rcm"
tmux -2 new-window     -kt $SESSION:9  -c "$BASEDIR/ar-api"           -n "arapi"
tmux -2 new-window     -kt $SESSION:10 -c "$BASEDIR/dcs-server"       -n "dsrv"
tmux -2 new-window     -kt $SESSION:11 -c "$BASEDIR/dcs"              -n "dcs"
tmux -2 select-window  -t $SESSION:2
