#!/bin/bash

SESSION=`basename "$0"`
BASEDIR="$HOME/github/9ci"
alias cddev="cd $BASEDIR"

tmux -2 new-session   -d -s "$SESSION" -c "$BASEDIR" -n "$BASEDIR"
tmux -2 new-window     -kt $SESSION:1  -c "$BASEDIR/rootLocation" -n "rootLocation"
tmux -2 new-window     -kt $SESSION:2  -c "$BASEDIR/nine-db"      -n "nine-db"
tmux -2 new-window     -kt $SESSION:3  -c "$BASEDIR/domain9"      -n "domain9"
tmux -2 new-window     -kt $SESSION:4  -c "$BASEDIR/lke-rancher"  -n "lke-rancher"
tmux -2 new-window     -kt $SESSION:5  -c "$BASEDIR/cust-rndc"    -n "cust-rndc"
tmux -2 new-window     -kt $SESSION:6  -c "$BASEDIR/go-rndc"      -n "go-rndc"
tmux -2 new-window     -kt $SESSION:7  -c "$BASEDIR/rcm-ui"       -n "rcm-ui"
tmux -2 new-window     -kt $SESSION:8  -c "$BASEDIR/vault"        -n "vault"
tmux -2 select-window  -t $SESSION:5
