#!/bin/bash

SESSION=`basename "$0"`
BASEDIR="$HOME/ws/dev"
alias cddev="cd $BASEDIR"

tmux -2 new-session   -d -s "$SESSION" -c "$BASEDIR" -n "$BASEDIR"
tmux -2 new-window     -kt $SESSION:1  -c "$BASEDIR/rootLocation"     -n "rootLocation"
tmux -2 new-window     -kt $SESSION:2  -c "$BASEDIR/shipkit"          -n "shipkit"
tmux -2 new-window     -kt $SESSION:3  -c "$BASEDIR/gorm-tools"       -n "gorm-tools"
tmux -2 select-window  -t $SESSION:2
