#!/bin/bash

SESSION=`basename "$0"`
BASEDIR="$HOME/ws/dev/head"
alias cddev="cd $BASEDIR"

tmux -2 new-session   -d -s "$SESSION" -c "$BASEDIR" -n "$BASEDIR"
tmux -2 new-window     -kt $SESSION:1  -c "$BASEDIR/rootLocation"     -n "rootLocation"
tmux -2 new-window     -kt $SESSION:2  -c "$BASEDIR/nine-db"          -n "nine-db"
tmux -2 new-window     -kt $SESSION:3  -c "$BASEDIR/angle-grinder"    -n "grndr"
tmux -2 new-window     -kt $SESSION:4  -c "$BASEDIR/rally"            -n "rally"
tmux -2 new-window     -kt $SESSION:5  -c "$BASEDIR/ar"               -n "ar"
tmux -2 new-window     -kt $SESSION:6  -c "$BASEDIR/autocash"         -n "cash"
tmux -2 new-window     -kt $SESSION:7  -c "$BASEDIR/payment-gateway"  -n "pg"
tmux -2 new-window     -kt $SESSION:8  -c "$BASEDIR/epay"             -n "epay"
tmux -2 new-window     -kt $SESSION:9  -c "$BASEDIR/rcm"              -n "rcm"
tmux -2 new-window     -kt $SESSION:10 -c "$BASEDIR/ar-api"           -n "arapi"
tmux -2 new-window     -kt $SESSION:11 -c "$BASEDIR/greenbill-api"    -n "gbapi"
tmux -2 new-window     -kt $SESSION:12 -c "$BASEDIR/carquest-scripts" -n "cqscripts"
tmux -2 new-window     -kt $SESSION:13 -c "$BASEDIR/sherwin-oracle"   -n "sw-oracle"
tmux -2 new-window     -kt $SESSION:14 -c "$BASEDIR/dcs-server"       -n "dsrv"
tmux -2 new-window     -kt $SESSION:15 -c "$BASEDIR/dcs"              -n "dcs"
tmux -2 new-window     -kt $SESSION:16 -c "$BASEDIR/nine-history"     -n "hist"
tmux -2 select-window  -t $SESSION:2
