#!/bin/bash

SESSION=`basename "$0"`
BASEDIR="$HOME/ws/docs"
alias cddocs="cd $BASEDIR"

tmux -2 new-session   -d -s "$SESSION" -c "$BASEDIR" -n "$BASEDIR"
tmux -2 new-window     -kt $SESSION:1  -c "$BASEDIR/9ci.github.io"  -n "9ci.github.io"
tmux -2 new-window     -kt $SESSION:2  -c "$BASEDIR/cust-aap"       -n "cust-aap"
tmux -2 new-window     -kt $SESSION:3  -c "$BASEDIR/cust-ced"       -n "cust-ced"
tmux -2 new-window     -kt $SESSION:4  -c "$BASEDIR/cust-manual"    -n "cust-manual"
tmux -2 new-window     -kt $SESSION:5  -c "$BASEDIR/cust-starter"   -n "cust-starter"
tmux -2 new-window     -kt $SESSION:6  -c "$BASEDIR/knowledge-base" -n "knowledge-base"
tmux -2 new-window     -kt $SESSION:7  -c "$BASEDIR/k9"             -n "k9"
tmux -2 new-window     -kt $SESSION:8  -c "$BASEDIR/9ci"            -n "9ci"
tmux -2 new-window     -kt $SESSION:9  -c "$BASEDIR/documentation"  -n "documentation"
tmux -2 select-window  -t $SESSION:1
