#!/bin/bash

SESSION=`basename "$0"`
BASEDIR="$HOME/github/grails"
alias cdmisc="cd $BASEDIR"

tmux -2 new-session   -d -s "$SESSION" -c "$BASEDIR"                     -n "$BASEDIR"
tmux -2 new-window     -kt $SESSION:1  -c "$BASEDIR/gorm-hibernate5"     -n "gorm-hibernate5"
tmux -2 new-window     -kt $SESSION:2  -c "$BASEDIR/grails-core"         -n "grails-core"
tmux -2 new-window     -kt $SESSION:3  -c "$BASEDIR/grails-data-mapping" -n "grails-data-mapping"
tmux -2 select-window  -t  $SESSION:2
