#!/bin/bash

SESSION=`basename "$0"`
BASEDIR="$HOME/ws/ken-roberts"

tmux -2 new-session   -d -s "$SESSION" -c "$BASEDIR" -n "$BASEDIR"
tmux -2 new-window     -kt $SESSION:1  -c "$BASEDIR/foster-db"      -n "foster-db"
tmux -2 new-window     -kt $SESSION:2  -c "$BASEDIR/foster-base"    -n "foster-base"
tmux -2 select-window  -t $SESSION:0
