#!/bin/bash

SESSION=`basename "$0"`
BASEDIR="$HOME/ws/ken-roberts"
alias cdkr="cd $BASEDIR"

tmux -2 new-session -d -s "$SESSION"   -c "/usr/local/krstuff"      -n "krstuff"
tmux -2 new-window     -kt $SESSION:1  -c "$HOME/.krstuff"          -n ".krstuff"
tmux -2 new-window     -kt $SESSION:2  -c "$BASEDIR/foster-db"      -n "foster-db"
tmux -2 new-window     -kt $SESSION:3  -c "$BASEDIR/foster-base"    -n "foster-base"
#tmux -2 new-window     -kt $SESSION:1  -c "$BASEDIR/q"               -n "q"
tmux -2 select-window  -t $SESSION:0
