#!/bin/bash

SESSION=`basename "$0"`
BASEDIR="$HOME/.krstuff"
alias cdkr="cd $BASEDIR"

tmux -2 new-session   -d -s "$SESSION" -c "$BASEDIR" -n "$BASEDIR"
tmux -2 new-window     -kt $SESSION:1  -c "$HOME/.krstuff/tmux.d"     -n "tmux.d"
tmux -2 new-window     -kt $SESSION:2  -c "/usr/local/krstuff"        -n "/usr/local/krstuff"
tmux -2 new-window     -kt $SESSION:3  -c "/usr/local/krstuff/tmux.d" -n "/usr/local/krstuff/tmux.d"
tmux -2 select-window  -t $SESSION:1
