#!/bin/bash

SESSION=`basename "$0"`
BASEDIR="$HOME/.krstuff"
alias cdkr="cd $BASEDIR"

tmux -2 new-session   -d -s "$SESSION" -c "$BASEDIR" -n "$BASEDIR"
tmux -2 new-window     -kt $SESSION:1  -c "$HOME/.krstuff/etc.d"                  -n "etc.d"
tmux -2 new-window     -kt $SESSION:2  -c "$HOME/.krstuff/platform_etc.d"         -n "platform_etc.d"
tmux -2 new-window     -kt $SESSION:3  -c "$HOME/.krstuff/tmux.d"                 -n "tmux.d"
tmux -2 new-window     -kt $SESSION:4  -c "$HOME/.krstuff/user_profile.d"         -n "user_profile.d"
tmux -2 new-window     -kt $SESSION:5  -c "/usr/local/krstuff"                    -n "KRS"
tmux -2 new-window     -kt $SESSION:6  -c "/usr/local/krstuff/bin"                -n "KRS/bin"
tmux -2 new-window     -kt $SESSION:7  -c "/usr/local/krstuff/etc.d"              -n "KRS/etc.d"
tmux -2 new-window     -kt $SESSION:8  -c "/usr/local/krstuff/platform_profile.d" -n "KRS/platform_profile.d"
tmux -2 new-window     -kt $SESSION:9  -c "/usr/local/krstuff/tmux.d"             -n "KRS/tmux.d"
tmux -2 select-window  -t $SESSION:3
