#!/bin/bash

SESSION=`basename "$0"`
BASEDIR="$HOME/github/yakworks"
alias cdmisc="cd $BASEDIR"

tmux -2 new-session   -d -s "$SESSION" -c "$BASEDIR"                    -n "$BASEDIR"
tmux -2 new-window     -kt $SESSION:1  -c "$BASEDIR/dockers"            -n "dockers"
tmux -2 new-window     -kt $SESSION:2  -c "$BASEDIR/docmark"            -n "docmark"
tmux -2 new-window     -kt $SESSION:3  -c "$BASEDIR/gorm-tools"         -n "gorm-tools"
tmux -2 new-window     -kt $SESSION:4  -c "$BASEDIR/gradle-plugins"     -n "gradle-plugins"
tmux -2 new-window     -kt $SESSION:5  -c "$BASEDIR/grails-audit-trail" -n "grails-audit-trail"
tmux -2 new-window     -kt $SESSION:6  -c "$BASEDIR/shipkit"            -n "shipkit"
tmux -2 new-window     -kt $SESSION:7  -c "$BASEDIR/view-tools"         -n "view-tools"
tmux -2 select-window  -t  $SESSION:3
