# Ken Roberts 2021-08-04

krstuff_log 'Entering'

CATALINA_OPTS='-Xmx2048M'
CLASSPATH='../rootLocation/conf'
GRAILS_OPTS='-Xmx2048M'
JAVA_OPTS="-Xmx2048m"
GRAILS_PRINTWIDTH=140
GITHUB_TOKEN="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"
MAVEN_REPO_USER='ken'
MAVEN_REPO_KEY='DVIpM7x9Wkw3'
ARTIFACTORY_USER='9cibot'
ARTIFACTORY_PASSWORD='999Pl4z4dr1ve'
CIRCLE_TOKEN='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'
GRGIT_USER="$GITHUB_TOKEN"
POSTGRES_PASSWORD='123Foobar'

export CATALINA_OPTS CLASSPATH GRAILS_OPTS JAVA_OPTS GRAILS_PRINTWIDTH GITHUB TOKEN MAVEN_REPO_USER MAVEN_REPO_KEY ARTIFACTORY_USER ARTIFACTORY_PASSWORD CIRCLE_TOKEN GRGIT_USER POSTGRES_PASSWORD

krstuff_log 'Leaving'
